api/urls.py
from django.urls import path , include
from .views import PostViewSet , UserViewSet , AuthorView
from django.views.generic import TemplateView
from rest_framework import routers


app_name = 'api'




router = routers.SimpleRouter()
router.register('users', UserViewSet ,basename="users")
router.register('posts', PostViewSet , basename="posts")


urlpatterns = [
    path('' , include(router.urls)),
    path('authors/<int:pk>/' , AuthorView.as_view() ,name="author-detail")
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
# from rest_framework.authtoken.views import obtain_auth_token
from dj_rest_auth.views import PasswordResetConfirmView
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/rest-auth/registration/password/reset/confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'post'




urlpatterns = [
    path('',views.PostListView.as_view(),name='post-list'),
    path('<int:pk>',views.PostDetailView.as_view(),name='post-detail'),
    path ('add_post/',views.add_post,name='add_post'),
    path ('update_post/<int:pk>',views.update_post,name='update_post'),
]

api/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.




class Post(models.Model):
    STATUS_CHOICES = (
        ('pub' , 'Published'),
        ('drf' , 'draft'),
    )
    text = models.TextField()
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES)

posts/forms.py
from django import forms
from .models import Post




class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text','author','status')

api/views.py
from rest_framework.generics import ListCreateAPIView ,RetrieveUpdateDestroyAPIView,RetrieveAPIView
from posts.models import Post
from .serializers import PostSerializer ,UserSerializer, AuthorSerializer
from django.contrib.auth import get_user_model
from rest_framework.permissions import IsAdminUser , AllowAny
from .permissions import IsSuperUser,IsStaffOrReadOnly,IsAuthorOrReadOnly,IsSuperUserOrIsStaffReadOnly
from rest_framework.viewsets import ModelViewSet







class PostViewSet(ModelViewSet):
	
	queryset = Post.objects.all()
	serializer_class = PostSerializer
	filterset_fields = ['status', 'author__username']
	ordering_fields = ['status', 'created']
	search_fields = [
		'text',
		'author__username',
		'author__first_name',
		'author__last_name',
	]

	def get_permissions(self):
		if self.action in ['list','create']:
			permission_classes = [AllowAny]
		else:
			permission_classes = [IsAuthorOrReadOnly]
		return [permission() for permission in permission_classes]
		



class UserViewSet(ModelViewSet):
	queryset = get_user_model().objects.all()
	serializer_class = UserSerializer
	def get_permissions(self):
		if self.action in ['list','create']:
			permission_classes = [IsSuperUserOrIsStaffReadOnly]
		else:
			permission_classes = [IsSuperUser]
		return [permission() for permission in permission_classes]
	

class AuthorView(RetrieveAPIView):
	queryset = get_user_model().objects.all()
	serializer_class = AuthorSerializer

posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView , DetailView
from .models import Post
from .forms import PostForm
# Create your views here.


# def home(request):
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'post_list.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    template_name = 'post_detail.html'
    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Post, pk=pk)






















def add_post(request):
    template = 'add_post.html'
    form = PostForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('post:home')
    context = {"form":form}

    return render(request, template , context)


def update_post(request , pk):
    template = 'update_post.html'
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect('post:home')

    context = {"form":form}

    return render(request, template , context)

templates/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">New Post</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="row" style="height: 120px; background-color: aqua;"></div>
      <form method="POST">{% csrf_token %}
          {{form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
      </form>










    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'post:post-list' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:add_post' %}">New Post</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="row" style="height: 120px; background-color: aqua;"></div>
      <div class="row mt-5 justify-content-center">
          <div class="col-4">
              {% block content %}

              {% endblock %}
          </div>
      </div>











    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/post_detail.html
{% extends 'base.html' %}








{% block content %}

<div class="card" style="width: 28rem;">
    
    <div class="card-body">
      <h5 class="card-title">by {{object.author}}</h5>
      <p class="card-text">{{object.text}}</p>
      
      <a href="#" class="btn btn-primary">Edit</a>
    </div>
</div>


{% endblock %}

templates/post_list.html
{% extends 'base.html' %}





{% block content %}
{% for post in posts %}
<div class="card" style="width: 28rem;">
    
    <div class="card-body">
      <h5 class="card-title">by {{post.author}}</h5>
      <p class="card-text">{{post.text}}</p>
      
      <a href="{% url 'post:post-detail' post.pk %}" class="btn btn-primary">view</a>
    </div>
</div>
{% endfor %}

{% endblock %}

templates/update_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">New Post</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="row" style="height: 120px; background-color: aqua;"></div>
      <form method="POST">{% csrf_token %}
          {{form.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
      </form>










    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>